dist: bionic
language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools



install:
  - pip3 install --user conan conan_package_tools cmake urllib3


script:
  - cmake . -B_build -DCMAKE_BUILD_TYPE=Debug && cmake --build _build -- -j2
  - cd _build
  - ctest -j2
