dist: trusty
language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake



install:
  - pip install --user conan cmake


script:
  - cmake . -B_build -DCMAKE_BUILD_TYPE=Debug && cmake --build _build
