dist: trusty
language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - python3
      - python3-pip



install:
  - pip install --user conan conan_package_tools cmake urllib3


script:
  - cmake . -B_build -DCMAKE_BUILD_TYPE=Debug && cmake --build _build
