dist: trusty
language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake



install:
  - pip install --user conan cmake


script:
  - g++ src/main.cpp
